name: ml4fl_py38
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- conda-forge::gdal>=3.1
- conda-forge::libgdal>=3.1
- pip
- pip:
  # PYTORCH ECOSYSTEM
  - torch
  - torchvision
  - pytorch-lightning
  - numpy
  - matplotlib
  - scipy
  - pandas
  - rasterio
  - geopandas
  - fastprogress
  - tqdm
  - black
  - isort
  - mypy