name: ml4floods-vis
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- conda-forge::geopandas # let geopandas and rasterio sort their own dependencies with gdal and pyproj
- conda-forge::rasterio
- pip
- pip:
  - torch
  - torchvision
  - ipykernel
  - google-cloud-storage
  - Flask
  - Flask-HTTPAuth
  - Flask-Login
  - Flask-WTF
  - gunicorn
  - google-cloud-storage
  - mercantile
  - pillow
